POTTERY_DICTIONARY_POTTERY_TYPE = "Pottery Type"
POTTERY_DICTIONARY_VESSEL_PART = "Pottery Vessel Part"
# PAC Chronology ConceptScheme (Q454). Its PAC URL is stable, whereas the
# Arches UUID generated by an RDF import differs between databases.
POTTERY_DICTIONARY_CHRONOLOGY = "https://pac.cenagis.edu.pl/entity/Q454"
POTTERY_DICTIONARY_SUB_CATEGORY = "Pottery Sub-category"
POTTERY_DICTIONARY_FORM = "Pottery Form"
POTTERY_DICTIONARY_TYPE = "Pottery Type/Form Classification"
POTTERY_DICTIONARY_PROVENANCE = "Pottery Provenance"
POTTERY_DICTIONARY_MORPHOLOGY = "Pottery Morphology"

POTTERY_VESSEL_PART_ALIASES = {
    "R": "Rim",
    "H": "Handle",
    "B": "Base",
    "W": "Wall",
}

# AMPHORAE CONSTANTS
AMPHORAE_GRAPH_ID = "e26f560f-da72-49cb-b4d4-8f7ab7e1ba74"
AMPHORAE_RELATED_COLLECTION_NODE_ID = "f7afd762-af38-4e2c-bbbf-1d287b3835a1"
AMPHORAE_COUNT_NODE_ID = "03b2d24c-4cc5-4141-b343-1feef0dc47b8"
AMPHORAE_PROVENANCE_NODE_ID = "f4121529-af9b-45ec-b6ea-048ceb659592"
AMPHORAE_DRAWN_NODE_ID = "b549463e-a538-4c68-a53d-8ac989d254a3"
AMPHORAE_POTTERY_TYPE_NODE_ID = None
AMPHORAE_MORPHOLOGY_NODE_ID = "514887c4-bf39-4843-b242-e97354e2ea9a"
AMPHORAE_SOURCE_ROW_NODE_ID = None
AMPHORAE_FORM_NO_NODE_ID = "f23494d4-ac45-4d8b-b9e3-8f70e7210c61"
AMPHORAE_PHOTO_NODE_ID = "94e584d0-ffff-4af1-b404-e8ad5ef30bd8"
AMPHORAE_VESSEL_PART_NODE_ID = "fecf88a3-90f7-4eca-94a8-7a68889e520c"
AMPHORAE_P_NO_NODE_ID = "e2ed5627-51c2-4e27-8a80-0198c7777b50"
AMPHORAE_SOURCE_SHEET_NODE_ID = None
AMPHORAE_CHRONOLOGY_NODE_ID = "f3c3489d-746a-46fa-8f94-90733a6f818e"
AMPHORAE_TYPE_NODE_ID = "d6865eb9-9975-4579-b7ac-2a5f6f2150fa"
AMPHORAE_PHOTO_RAW_NODE_ID = "94e584d0-ffff-4af1-b404-e8ad5ef30bd8"
AMPHORAE_CHRONOLOGY_NODEGROUP_ID = "267b8cb6-2f51-4940-bad0-f227b3ecc285"
AMPHORAE_CHRONOLOGY_UNCERTAIN_NODE_ID = "e3e506bc-dc57-4885-bd60-7dc6364a2e3a"
AMPHORAE_TYPE_UNCERTAIN_NODE_ID = "81f22bf7-8d45-43b1-97de-acb8ef601ebb"
AMPHORAE_PROVENANCE_UNCERTAIN_NODE_ID = "3373f822-366c-497e-94d0-ac81091bd36f"
AMPHORAE_SPECIAL_FIND_NODE_ID = "218ebfe5-9b80-40d1-a0e8-7c44f149bb95"
AMPHORAE_COMMENT_NODE_ID = "f5a44203-2acd-43e0-975e-7698e705c524"

# STORAGE VESSEL CONSTANTS
STORAGE_VESSEL_GRAPH_ID = "4a8fd9ec-bc7e-4e9f-8e14-47c6e3d9797f"
STORAGE_VESSEL_P_NO_NODE_ID = "db9e4c88-1b7d-40b0-9331-a181412899d1"
STORAGE_VESSEL_PHOTO_NODE_ID = "d87c0594-68af-48c1-8b32-e31da4386b09"
STORAGE_VESSEL_SOURCE_SHEET_NODE_ID = "3349c591-347a-43ed-81bf-09c9d9f6f6b5"
STORAGE_VESSEL_POTTERY_TYPE_NODE_ID = "f8081496-93b0-4bec-97d2-ab0f17154bff"
STORAGE_VESSEL_MORPHOLOGY_NODE_ID = "57080a18-8561-4fbd-8a1f-a1d785d393db"
STORAGE_VESSEL_SOURCE_ROW_NODE_ID = "0dc6ffeb-bf02-4c3c-ae63-753093f81552"
STORAGE_VESSEL_COUNT_NODE_ID = "7295249b-52c0-45ff-9ab9-569a5b529235"
STORAGE_VESSEL_FORM_NODE_ID = "f842c6e9-f77e-45ad-a538-568616d510a4"
STORAGE_VESSEL_TYPE_NODE_ID = "0610470e-e140-4468-8d22-f1a1d142e71f"
STORAGE_VESSEL_FORM_NO_NODE_ID = "d132a517-0cd1-45dd-a8f3-2f2c94769b38"
STORAGE_VESSEL_CHRONOLOGY_NODE_ID = "e694aa1b-a1c5-4bb9-86d6-cba2f9639a99"
STORAGE_VESSEL_DRAWN_NODE_ID = "a82c7334-e495-4078-9b29-cd5b1ad7088b"
STORAGE_VESSEL_PROVENANCE_NODE_ID = "63f6e308-0275-4c2d-9ca4-0e555bc38bc8"
STORAGE_VESSEL_TW_MG_NO_NODE_ID = "be1cee50-e4fa-48b9-949a-e8ebc83ca19c"
STORAGE_VESSEL_RELATED_COLLECTION_NODE_ID = "03e83599-108e-4ee2-a3c0-7c63c9f42807"
STORAGE_VESSEL_VESSEL_PART_NODE_ID = "eb7abbc6-e725-4034-8a9c-3731fa71a779"

# TABLE WARE CONSTANTS
TABLE_WARE_GRAPH_ID = "ade283ce-5d7e-4d87-af1a-afba2bb8a6ea"
TABLE_WARE_RELATED_COLLECTION_NODE_ID = "05067c8b-514d-4d17-8caa-e5b0ebd0eb8b"
TABLE_WARE_PROVENANCE_NODE_ID = "47a3ebef-6818-4aee-8b64-2a478cd3022f"
TABLE_WARE_SOURCE_SHEET_NODE_ID = "a60d5dca-5184-49c1-9f8d-83721579a759"
TABLE_WARE_SOURCE_ROW_NODE_ID = "5caa6b71-e133-4829-8927-fecc05e456d7"
TABLE_WARE_FORM_NODE_ID = "0a16fed9-0a47-4bb1-930c-5159f69e5692"
TABLE_WARE_VESSEL_PART_NODE_ID = "aea61efe-7102-4a28-bba4-e8ecdc98b150"
TABLE_WARE_TYPE_NODE_ID = "c06ca7b0-9632-45a2-8e75-0b7657ba3961"
TABLE_WARE_COUNT_NODE_ID = "bd9ec5d3-caea-48c9-92ee-6a0afd65e420"
TABLE_WARE_DRAWN_NODE_ID = "5caab80f-9734-446f-a3b7-3eabb1fbb7bb"
TABLE_WARE_PHOTO_NODE_ID = "1d451706-5243-4562-875a-d6a101f2a107"
TABLE_WARE_TW_MG_NO_NODE_ID = "b3970403-3226-47ee-b828-fc5775e22cb6"
TABLE_WARE_SUB_CATEGORY_NODE_ID = "b6678fb2-05bd-4598-934f-da237f3ae615"
TABLE_WARE_FORM_NO_NODE_ID = "3acc57ee-4a30-4944-ace8-5538f6078db0"
TABLE_WARE_MORPHOLOGY_NODE_ID = "0d1fac40-8e4e-42e1-84e1-ab37e08368c0"
TABLE_WARE_P_NO_NODE_ID = "67d00b69-f1f2-4d30-9f14-09eb3b84219f"
TABLE_WARE_CHRONOLOGY_NODE_ID = "b8f06427-d89b-490d-bba9-6610b4d59f88"
TABLE_WARE_POTTERY_TYPE_NODE_ID = "b2539766-6f19-40d4-ae50-831646f42b2d"
POTTERY_RECORD_TYPES = {
    "amphorae": {
        "label": "Amphorae",
        "graph_id": AMPHORAE_GRAPH_ID,
        "related_collection_node_id": AMPHORAE_RELATED_COLLECTION_NODE_ID,
        "pottery_type_node_id": AMPHORAE_POTTERY_TYPE_NODE_ID,
        "source_sheet_node_id": AMPHORAE_SOURCE_SHEET_NODE_ID,
        "source_row_node_id": AMPHORAE_SOURCE_ROW_NODE_ID,
        "sheet_priority": ["Table", "Data"],
        "dictionary_required": True,
        "dictionary_fields": {
            "potteryType": POTTERY_DICTIONARY_POTTERY_TYPE,
            "vesselPart": POTTERY_DICTIONARY_VESSEL_PART,
            "type": POTTERY_DICTIONARY_TYPE,
            "morphology": POTTERY_DICTIONARY_MORPHOLOGY,
            "chronology": POTTERY_DICTIONARY_CHRONOLOGY,
            "provenance": POTTERY_DICTIONARY_PROVENANCE,
        },
        "dictionary_aliases": {
            "vesselPart": POTTERY_VESSEL_PART_ALIASES,
        },
        "fields": {
            "formNo": AMPHORAE_FORM_NO_NODE_ID,
            "pNo": AMPHORAE_P_NO_NODE_ID,
            "count": AMPHORAE_COUNT_NODE_ID,
            "vesselPart": AMPHORAE_VESSEL_PART_NODE_ID,
            "type": AMPHORAE_TYPE_NODE_ID,
            "morphology": AMPHORAE_MORPHOLOGY_NODE_ID,
            "chronology": AMPHORAE_CHRONOLOGY_NODE_ID,
            "provenance": AMPHORAE_PROVENANCE_NODE_ID,
            "drawn": AMPHORAE_DRAWN_NODE_ID,
            "photo": AMPHORAE_PHOTO_RAW_NODE_ID,
            "typeUncertain": AMPHORAE_TYPE_UNCERTAIN_NODE_ID,
            "chronologyUncertain": AMPHORAE_CHRONOLOGY_UNCERTAIN_NODE_ID,
            "provenanceUncertain": AMPHORAE_PROVENANCE_UNCERTAIN_NODE_ID,
            "comment": AMPHORAE_COMMENT_NODE_ID,
        },
        "columns": [
            {"key": "formNo", "label": "Form_no"},
            {"key": "pNo", "label": "p_no"},
            {"key": "count", "label": "Count"},
            {"key": "vesselPart", "label": "VESSEL_PART"},
            {"key": "type", "label": "TYPE"},
            {"key": "morphology", "label": "MORPHOLOGY"},
            {"key": "chronology", "label": "CHRONOLOGY"},
            {"key": "provenance", "label": "PROVENANCE"},
            {"key": "drawn", "label": "DRAWN"},
            {"key": "photo", "label": "PHOTO"},
            {"key": "typeUncertain", "label": "TYPE UNCERTAIN"},
            {"key": "chronologyUncertain", "label": "CHRONOLOGY UNCERTAIN"},
            {"key": "provenanceUncertain", "label": "PROVENANCE UNCERTAIN"},
            {"key": "comment", "label": "COMMENT"},
            {"key": "resourceLink", "label": "Resource"},
        ],
        "excel_fields": {
            "vesselPart": ["vessel_part"],
            "type": ["type"],
            "morphology": ["morphology"],
            "chronology": ["chronology"],
            "provenance": ["provenance"],
            "drawn": ["drawn"],
            "photo": ["photo"],
        },
        "record_data_keys": [
            "pNo",
            "count",
            "vesselPart",
            "type",
            "morphology",
            "chronology",
            "provenance",
        ],
    },
    "storage-vessel": {
        "label": "Storage Vessel",
        "graph_id": STORAGE_VESSEL_GRAPH_ID,
        "related_collection_node_id": STORAGE_VESSEL_RELATED_COLLECTION_NODE_ID,
        "pottery_type_node_id": STORAGE_VESSEL_POTTERY_TYPE_NODE_ID,
        "source_sheet_node_id": STORAGE_VESSEL_SOURCE_SHEET_NODE_ID,
        "source_row_node_id": STORAGE_VESSEL_SOURCE_ROW_NODE_ID,
        "sheet_priority": ["Table", "Data"],
        "dictionary_required": True,
        "dictionary_fields": {
            "potteryType": POTTERY_DICTIONARY_POTTERY_TYPE,
            "vesselPart": POTTERY_DICTIONARY_VESSEL_PART,
            "morphology": POTTERY_DICTIONARY_MORPHOLOGY,
            "form": POTTERY_DICTIONARY_FORM,
            "type": POTTERY_DICTIONARY_TYPE,
            "chronology": POTTERY_DICTIONARY_CHRONOLOGY,
            "provenance": POTTERY_DICTIONARY_PROVENANCE,
        },
        "dictionary_aliases": {
            "vesselPart": POTTERY_VESSEL_PART_ALIASES,
        },
        "fields": {
            "formNo": STORAGE_VESSEL_FORM_NO_NODE_ID,
            "pNo": STORAGE_VESSEL_P_NO_NODE_ID,
            "twMgNo": STORAGE_VESSEL_TW_MG_NO_NODE_ID,
            "vesselPart": STORAGE_VESSEL_VESSEL_PART_NODE_ID,
            "morphology": STORAGE_VESSEL_MORPHOLOGY_NODE_ID,
            "form": STORAGE_VESSEL_FORM_NODE_ID,
            "type": STORAGE_VESSEL_TYPE_NODE_ID,
            "chronology": STORAGE_VESSEL_CHRONOLOGY_NODE_ID,
            "provenance": STORAGE_VESSEL_PROVENANCE_NODE_ID,
            "drawn": STORAGE_VESSEL_DRAWN_NODE_ID,
            "photo": STORAGE_VESSEL_PHOTO_NODE_ID,
        },
        "columns": [
            {"key": "formNo", "label": "Form_no"},
            {"key": "pNo", "label": "p_no"},
            {"key": "twMgNo", "label": "TW_MG_no"},
            {"key": "vesselPart", "label": "VESSEL_PART"},
            {"key": "morphology", "label": "MORPHOLOGY"},
            {"key": "form", "label": "FORM"},
            {"key": "type", "label": "TYPE"},
            {"key": "chronology", "label": "CHRONOLOGY"},
            {"key": "provenance", "label": "PROVENANCE"},
            {"key": "drawn", "label": "DRAWN"},
            {"key": "photo", "label": "PHOTO"},
            {"key": "typeUncertain", "label": "TYPE UNCERTAIN"},
            {"key": "chronologyUncertain", "label": "CHRONOLOGY UNCERTAIN"},
            {"key": "provenanceUncertain", "label": "PROVENANCE UNCERTAIN"},
            {"key": "comment", "label": "COMMENT"},
            {"key": "resourceLink", "label": "Resource"},
        ],
        "excel_fields": {
            "twMgNo": ["tw_mg_no"],
            "vesselPart": ["vessel_part"],
            "morphology": ["morphology"],
            "form": ["form"],
            "type": ["type"],
            "chronology": ["chronology"],
            "provenance": ["provenance"],
            "drawn": ["drawn"],
            "photo": ["photo"],
        },
        "record_data_keys": [
            "pNo",
            "count",
            "twMgNo",
            "vesselPart",
            "morphology",
            "form",
            "type",
            "chronology",
            "provenance",
        ],
    },
    "table-ware": {
        "label": "Table Ware",
        "graph_id": TABLE_WARE_GRAPH_ID,
        "related_collection_node_id": TABLE_WARE_RELATED_COLLECTION_NODE_ID,
        "pottery_type_node_id": TABLE_WARE_POTTERY_TYPE_NODE_ID,
        "source_sheet_node_id": TABLE_WARE_SOURCE_SHEET_NODE_ID,
        "source_row_node_id": TABLE_WARE_SOURCE_ROW_NODE_ID,
        "sheet_priority": ["Data", "Table"],
        "dictionary_required": True,
        "dictionary_fields": {
            "potteryType": POTTERY_DICTIONARY_POTTERY_TYPE,
            "subCategory": POTTERY_DICTIONARY_SUB_CATEGORY,
            "vesselPart": POTTERY_DICTIONARY_VESSEL_PART,
            "morphology": POTTERY_DICTIONARY_MORPHOLOGY,
            "form": POTTERY_DICTIONARY_FORM,
            "type": POTTERY_DICTIONARY_TYPE,
            "chronology": POTTERY_DICTIONARY_CHRONOLOGY,
            "provenance": POTTERY_DICTIONARY_PROVENANCE,
        },
        "dictionary_aliases": {
            "vesselPart": POTTERY_VESSEL_PART_ALIASES,
        },
        "fields": {
            "formNo": TABLE_WARE_FORM_NO_NODE_ID,
            "pNo": TABLE_WARE_P_NO_NODE_ID,
            "twMgNo": TABLE_WARE_TW_MG_NO_NODE_ID,
            "subCategory": TABLE_WARE_SUB_CATEGORY_NODE_ID,
            "vesselPart": TABLE_WARE_VESSEL_PART_NODE_ID,
            "morphology": TABLE_WARE_MORPHOLOGY_NODE_ID,
            "form": TABLE_WARE_FORM_NODE_ID,
            "type": TABLE_WARE_TYPE_NODE_ID,
            "chronology": TABLE_WARE_CHRONOLOGY_NODE_ID,
            "provenance": TABLE_WARE_PROVENANCE_NODE_ID,
            "drawn": TABLE_WARE_DRAWN_NODE_ID,
            "photo": TABLE_WARE_PHOTO_NODE_ID,
        },
        "columns": [
            {"key": "formNo", "label": "Form_no"},
            {"key": "pNo", "label": "p_no"},
            {"key": "twMgNo", "label": "TW_MG_no"},
            {"key": "subCategory", "label": "SUB-CATEGORY"},
            {"key": "form", "label": "FORM"},
            {"key": "type", "label": "TYPE"},
            {"key": "vesselPart", "label": "VESSEL_PART"},
            {"key": "morphology", "label": "MORPHOLOGY"},
            {"key": "chronology", "label": "CHRONOLOGY"},
            {"key": "provenance", "label": "PROVENANCE"},
            {"key": "drawn", "label": "DRAWN"},
            {"key": "photo", "label": "PHOTO"},
            {"key": "typeUncertain", "label": "TYPE UNCERTAIN"},
            {"key": "chronologyUncertain", "label": "CHRONOLOGY UNCERTAIN"},
            {"key": "provenanceUncertain", "label": "PROVENANCE UNCERTAIN"},
            {"key": "comment", "label": "COMMENT"},
            {"key": "resourceLink", "label": "Resource"},
        ],
        "excel_fields": {
            "twMgNo": ["tw_mg_no"],
            "subCategory": ["sub_category", "subcategory"],
            "vesselPart": ["vessel_part"],
            "morphology": ["morphology"],
            "form": ["form"],
            "type": ["type"],
            "chronology": ["chronology"],
            "provenance": ["provenance"],
            "drawn": ["drawn"],
            "photo": ["photo"],
        },
        "record_data_keys": [
            "pNo",
            "count",
            "twMgNo",
            "subCategory",
            "vesselPart",
            "morphology",
            "form",
            "type",
            "chronology",
            "provenance",
        ],
    },
}
